const title = document.getElementById('title')
console.log(title)
console.log(typeof title)
title.textContent = 'Good Job'
const item = document.getElementsByClassName('item')
console.log(item)
console.log(typeof item)
console.log(item[0])
console.log(item[1])
console.log(item[2])
const liList = document.getElementsByTagName('li')
console.log(liList)
const $title = document.querySelector('#title')
console.log($title)
const $item = document.querySelector('.item')
console.log($item)
const $items = document.querySelectorAll('.item')
console.log($items)